package startup

import (
	"github.com/Nebojsa1999/XMLProjekat/agent-app-backend/domain"
	"github.com/Nebojsa1999/XMLProjekat/agent-app-backend/domain/enums"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var users = []*domain.User{
	{
		Id:                     getObjectId("123a0cc3a34d25d8567f9f01"),
		Role:                   enums.CommonUser,
		OwnedCompanyId:         primitive.NilObjectID,
		IssuedCompanyRequestId: getObjectId("123a0cc3a34d25d8567f9f02"),
		Username:               "Darijan98",
		Password:               "darijan",
		FirstName:              "Darijan",
		LastName:               "Mićić",
		Email:                  "darijan.micic10@gmail.com",
		Phone:                  "062/100-6031",
		Gender:                 enums.Male,
		DateOfBirth:            getParsedDateOfBirthFrom("1998-07-10T00:00:00Z"),
		Biography:              "Biografija Darijana Mićića.",
		WorkExperience:         "Bez radnog iskustva.",
		Education:              "Fakultet tehničkih nauka Novi Sad",
		Skills:                 "Veb programiranje.",
		Interests:              "Video igre.",
	},
	{
		Id:                     getObjectId("123a0cc3a34d25d8567f9f02"),
		Role:                   enums.Administrator,
		OwnedCompanyId:         primitive.NilObjectID,
		IssuedCompanyRequestId: primitive.NilObjectID,
		Username:               "Nebojsa99",
		Password:               "nebojsa",
		FirstName:              "Nebojša",
		LastName:               "Bogosavljev",
		Email:                  "nebojsa.bogosavljev@gmail.com",
		Phone:                  "064/788-400",
		Gender:                 enums.Male,
		DateOfBirth:            getParsedDateOfBirthFrom("1999-09-26T00:00:00Z"),
		Biography:              "Biografija Nebojše Bogosavljeva.",
		WorkExperience:         "Bez radnog iskustva",
		Education:              "Fakultet tehničkih nauka Novi Sad",
		Skills:                 "Programer WPF aplikacija.",
		Interests:              "Video igre.",
	},
	{
		Id:                     getObjectId("123a0cc3a34d25d8567f9f03"),
		Role:                   enums.CommonUser,
		OwnedCompanyId:         primitive.NilObjectID,
		IssuedCompanyRequestId: primitive.NilObjectID,
		Username:               "Aleksandar97",
		Password:               "aleksandar",
		FirstName:              "Aleksandar",
		LastName:               "Dujin",
		Email:                  "aleksandar.dujin@gmail.com",
		Phone:                  "060/132-345",
		Gender:                 enums.Male,
		DateOfBirth:            getParsedDateOfBirthFrom("1997-02-03T00:00:00Z"),
		Biography:              "Biografija Aleksandra Dujina.",
		WorkExperience:         "Bez radnog iskustva.",
		Education:              "Fakultet tehničkih nauka Novi Sad",
		Skills:                 "Veb programiranje.",
		Interests:              "Video igre.",
	},
	{
		Id:                     getObjectId("123a0cc3a34d25d8567f9f04"),
		Role:                   enums.CompanyOwner,
		OwnedCompanyId:         getObjectId("123a0cc3a34d25d8567f9f01"),
		IssuedCompanyRequestId: getObjectId("123a0cc3a34d25d8567f9f01"),
		Username:               "Marko99",
		Password:               "marko",
		FirstName:              "Marko",
		LastName:               "Trifunović",
		Email:                  "marko.trifunovic@gmail.com",
		Phone:                  "063/763-6897",
		Gender:                 enums.Male,
		DateOfBirth:            getParsedDateOfBirthFrom("1999-11-30T00:00:00Z"),
		Biography:              "Biografija Marka Trifunovića.",
		WorkExperience:         "Bez radnog iskustva.",
		Education:              "Fakultet tehničkih nauka Novi Sad",
		Skills:                 "Programer WPF aplikacija.",
		Interests:              "Video igre.",
	},
}
